name: Windows Server 2022 - Tests

on: [push]

env:
  GO_VERSION: "^1.19.10"

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Build
        run: go build
