name: Tests

on: [push, pull_request]

env:
  GO_VERSION: "^1.19.10"

jobs:
  linux-compile:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: TEST_SUITE=compile go test -v ./...

  windows-2019-compile:
    name: Run Tests
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: TEST_SUITE=compile go test -v ./...

  windows-2022-compile:
    name: Run Tests
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: TEST_SUITE=compile go test -v ./...
