name: Windows Server 2019 - Tests

on: [push]

env:
  GO_VERSION: "^1.19.10"

jobs:
  js-no-cluster:
    name: JetStream - No Cluster
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v `
            -run TestJetStream `
            -tags "skip_js_cluster_tests,skip_js_cluster_tests_2,skip_js_cluster_tests_3,skip_js_super_cluster_tests" `
            -count 1 -vet off -timeout 30m -failfast `
            ./server/...

  js-cluster-1:
    name: JetStream Cluster - Test 1
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v `
            -run TestJetStreamCluster `
            -tags "skip_js_cluster_tests_2,skip_js_cluster_tests_3" `
            -count 1 -vet off -timeout 30m -failfast `
            ./server/...

  js-cluster-2:
    name: JetStream Cluster - Test 2
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v `
            -run TestJetStreamCluster `
            -tags "skip_js_cluster_tests,skip_js_cluster_tests_3" `
            -count 1 -vet off -timeout 30m -failfast `
            ./server/...

  js-cluster-3:
    name: JetStream Cluster - Test 3
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v `
            -run TestJetStreamCluster `
            -tags "skip_js_cluster_tests,skip_js_cluster_tests_2" `
            -count 1 -vet off -timeout 30m -failfast `
            ./server/...

  js-supercluster:
    name: JetStream Supercluster
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v `
            -run TestJetStreamSuperCluster `
            -count 1 -vet off -timeout 30m -failfast `
            ./server/...

  js-chaos:
    name: JetStream Chaos
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v -p 1 `
            -run TestJetStreamChaos `
            -tags "js_chaos_tests" `
            -count 1 -vet off -timeout 30m -failfast `
            ./server/...

  mqtt:
    name: MQTT
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v `
            -count 1 -vet off -timeout 30m -failfast `
            -run TestMQTT `
            ./server/...

  server-pkg-non-js:
    name: Server Package - Non-JS
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v -p 1 `
            -tags "skip_js_tests,skip_mqtt_tests" `
            -count 1 -vet off -timeout 30m -failfast `
            ./server/...

  non-server-pkg:
    name: Non-Server Package
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Run Tests
        run: |-
          go test -race -v -p 1 `
            -count 1 -vet off -timeout 30m -failfast `
            ./conf/... `
            ./internal/... `
            ./logger/... `
            ./test/...
