name: Tests

on: [push, pull_request]

env:
  GO_VERSION: "^1.19.10"

jobs:
  linux-compile:
    name: Linux - Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Deps
        run: go mod download

      - name: Build
        run: go build

      - name: Install GolangCI Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@6f7f8ae

      - name: Run GolangCI Lint
        run: golangci-lint run

  windows-2019-compile:
    name: Windows Server 2019 - Compile
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build

      - name: Install GolangCI Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@6f7f8ae

      - name: Run GolangCI Lint
        run: golangci-lint run

  windows-2022-compile:
    name: Windows Server 2022 - Compile
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build

      - name: Install GolangCI Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@6f7f8ae

      - name: Run GolangCI Lint
        run: golangci-lint run
